apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seafile.fullname" . }}-frontend
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
stringData:
  SEAFILE_DB_PROTOCOL: {{ include "seafile.databaseType.jdbc" .Values.frontend.database.type | quote }}
  SEAFILE_DB_TYPE: {{ .Values.frontend.database.type | quote }}
  SEAFILE_DB_HOST: {{ .Values.frontend.database.host | quote }}
  SEAFILE_DB_PORT: {{ .Values.frontend.database.port | quote }}
  SEAFILE_DB_USER: {{ .Values.frontend.database.username | quote }}
  SEAFILE_DB_PASSWORD: {{ .Values.frontend.database.password | quote }}
  REDIS_PASSWORD: {{ .Values.cache.password | quote }}
  JWT_PRIVATE_KEY: {{ .Values.jwtSecret | quote }}
