apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seafile.fullname" . }}-config
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
stringData:
  jwtSecret: {{ .Values.jwtSecret | quote }}
  ccnet.conf: |-
    [Database]
    ENGINE = {{ .Values.controller.database.type }}
    HOST = {{ .Values.controller.database.host }}
    PORT = {{ .Values.controller.database.port }}
    USER = {{ .Values.controller.database.username }}
    PASSWD = {{ .Values.controller.database.password }}
    {{- if eq "mysql" .Values.controller.database.type }}
    CONNECTION_CHARSET = utf8mb4
    {{- else }}
    CONNECTION_CHARSET = utf8
    {{- end }}
    
    [Client]
    UNIX_SOCKET = /run/seafile/seafile.sock
  seafile.conf: |-
    [database]
    type = {{ .Values.fileserver.database.type }}
    host = {{ .Values.fileserver.database.host }}
    port = {{ .Values.fileserver.database.port }}
    user = {{ .Values.fileserver.database.username }}
    password = {{ .Values.fileserver.database.password }}
    db_name = {{ .Values.fileserver.database.name }}
    {{- if eq "mysql" .Values.fileserver.database.type }}
    CONNECTION_CHARSET = utf8mb4
    {{- else }}
    CONNECTION_CHARSET = utf8
    {{- end }}
  seahub_settings.py: |-
    DATABASES = {
        'default': {
            'ENGINE': '{{ include "seafile.databaseType.django" .Values.frontend.database.type }}',
            'NAME': '{{ .Values.frontend.database.name }}',
            'USER': '{{ .Values.frontend.database.username }}',
            'PASSWORD': '{{ .Values.frontend.database.password }}',
            'HOST': '{{ .Values.frontend.database.host }}',
            'PORT': '{{ .Values.frontend.database.port }}',
        },
        'ccnet': {
            'ENGINE': '{{ include "seafile.databaseType.django" .Values.controller.database.type }}',
            'NAME': '{{ .Values.controller.database.name }}',
            'USER': '{{ .Values.controller.database.username }}',
            'PASSWORD': '{{ .Values.controller.database.password }}',
            'HOST': '{{ .Values.controller.database.host }}',
            'PORT': '{{ .Values.controller.database.port }}',
        },
        'seafile': {
            'ENGINE': '{{ include "seafile.databaseType.django" .Values.fileserver.database.type }}',
            'NAME': '{{ .Values.fileserver.database.name }}',
            'USER': '{{ .Values.fileserver.database.username }}',
            'PASSWORD': '{{ .Values.fileserver.database.password }}',
            'HOST': '{{ .Values.fileserver.database.host }}',
            'PORT': '{{ .Values.fileserver.database.port }}',
        }
    }
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': '{{ include "seafile.cacheUrl" . }}',
        }
    }
    
    FILE_SERVER_ROOT = '{{ include "seafile.fileserver.externalUrl" . }}/'
    INNER_FILE_SERVER_ROOT = '{{ include "seafile.fileserver.internalUrl" . }}'
    
    SERVICE_URL = '{{ include "seafile.frontend.externalUrl" . }}/'
    INNER_SERVICE_URL = '{{ include "seafile.frontend.internalUrl" . }}'

    CSRF_TRUSTED_ORIGINS = ["{{ include "seafile.frontend.externalUrl" . }}"]

    {{- if eq .Values.frontend.avatarStorage "database" }}
    AVATAR_FILE_STORAGE = 'seahub.base.database_storage.DatabaseStorage'
    {{- end }}
    
    #ONLYOFFICE_ROOT = "http://localhost:8080"
    #INNER_ONLYOFFICE_ROOT = "http://office"
    #
    #ENABLE_ONLYOFFICE = True
    #VERIFY_ONLYOFFICE_CERTIFICATE = False
    #ONLYOFFICE_APIJS_URL = 'http://localhost:8080/web-apps/apps/api/documents/api.js'
    #ONLYOFFICE_CONVERTER_URL = 'http://office/ConvertService.ashx'
    #ONLYOFFICE_FILE_EXTENSION = ('doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'odt', 'fodt', 'odp', 'fodp', 'ods', 'fods')
    #ONLYOFFICE_EDIT_FILE_EXTENSION = ('docx', 'pptx', 'xlsx')
    #
    #ONLYOFFICE_FORCE_SAVE = True
    #ONLYOFFICE_JWT_SECRET = '52d3d4f142b34b5dbec60ab59264e5cc'
