apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "seafile.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      name: frontend
      targetPort: frontend
    - port: 8082
      name: fileserver
      targetPort: fileserver
    - port: 8083
      name: notifications
      targetPort: notifications
