services:
  valkey:
    image: valkey/valkey:9.0.3
    command: --requirepass "password"
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "password", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  seafile:
    build:
      context: .
      dockerfile: seafile.dockerfile
    volumes:
      - seafile-data:/data
      - shared-run:/run/seafile
    environment:
      - SEAFILE_DB_USER=seafile
      - SEAFILE_DB_PASSWORD=password

  notifications:
    build:
      context: seafile-notifications
      dockerfile: Dockerfile
    volumes:
      - seafile-data:/data
      - shared-run:/run/seafile
    environment:
      - SEAFILE_DB_USER=seafile
      - SEAFILE_DB_PASSWORD=password
    ports:
      - "8083:8083"

  fileserver:
    build:
      context: seafile-fileserver
      dockerfile: Dockerfile
    volumes:
      - seafile-data:/data
      - shared-run:/run/seafile
    environment:
      - SEAFILE_DB_USER=seafile
      - SEAFILE_DB_PASSWORD=password
    ports:
      - "8082:8082"

  seahub:
    build:
      context: seahub
      dockerfile: Dockerfile
    volumes:
      - seafile-data:/data
      - shared-run:/run/seafile
    environment:
      - SEAFILE_DB_USER=seahub
      - SEAFILE_DB_PASSWORD=password
    ports:
      - "8000:8000"

  office:
    image: ghcr.io/euro-office/documentserver:latest
    environment:
      - JWT_SECRET=52d3d4f142b34b5dbec60ab59264e5cc
    ports:
      - "8080:80"

volumes:
  seafile-data:
  shared-run:
