services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/pgsql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    extends:
      file: base.yml
      service: valkey

  seafile:
    extends:
      file: base.yml
      service: seafile
    volumes:
      - ./config/pgsql:/config
    env_file:
      - pgsql.env
    depends_on:
      db:
        condition: service_healthy

  notifications:
    extends:
      file: base.yml
      service: notifications
    volumes:
      - ./config/pgsql:/config
    env_file:
      - pgsql.env
    depends_on:
      seafile:
        condition: service_started
      db:
        condition: service_healthy

  fileserver:
    extends:
      file: base.yml
      service: fileserver
    volumes:
      - ./config/pgsql:/config
    env_file:
      - pgsql.env
    depends_on:
      seafile:
        condition: service_started
      db:
        condition: service_healthy

  seahub:
    extends:
      file: base.yml
      service: seahub
    volumes:
      - ./config/pgsql:/config
    env_file:
      - pgsql.env
    depends_on:
      seafile:
        condition: service_started
      db:
        condition: service_healthy

  office:
    extends:
      file: base.yml
      service: office
    env_file:
      - pgsql.env

volumes:
  db-data:
  seafile-data:
  shared-run:
